### ISSUE TITLE
Jokes API

### ISSUE THREAD

**Issue by asim** [micro/services#124]
Leverage https://github.com/taivop/joke-dataset for a jokes api

**Comment by h1z3y3** [comment]
I'd like to help

**Comment by h1z3y3** [comment]
I'm going to implement this issue. 
But I'm a little confusing where to store the jokes resouces?
In Micro Store or just store them in the files ?

**Comment by asim** [comment]
Best to think about a repeatable process for loading the dataset, so they could be stored in the micro store, the blob store or a standard json file alongside the source code if its static.

**Comment by h1z3y3** [comment]
Got it.

And one more thing, when to store the materials into the store.
I think it's better to store them with the service starts, right?

**Comment by asim** [comment]
Yea I think a bootstrapping step is a good call. Basically; 1. check if the data exist, 2. if not download it and save it, 3. load it. A jokes dataset should be fairly small anyway. But ideally you can run micro locally, bootup the jokes api and it works identical to what it would on any other platform.
