### ISSUE TITLE
Run demo 'helloworld' failed

### ISSUE THREAD

**Issue by illegaluid** [micro/services#172]
When I try to run 'helloworld'
I got this 
`
~  micro run github.com/micro/services/helloworld
`
`
{"Id":"runtime.Runtime.Create","Code":401,"Detail":"An account is required","Status":"Unauthorized"}
`
and log info is this
 `
 file=cmd/util.go:133 level=warn [Auth] Error refreshing token: invalid token provided
`

**Comment by asim** [comment]
You must now login to use micro. You can use the default account user: admin, pass: micro

Do `micro login` to complete this.
