### ISSUE TITLE
micro services is giving connection closed error

### ISSUE THREAD

**Issue by sreenathac** [micro/services#177]
I am trying to run hellowrld example by following steps as per 
https://micro.mu/getting-started
I started micro server 
![image](https://user-images.githubusercontent.com/25299932/125202870-4cb60800-e293-11eb-9dcb-7ad32a54dbfe.png)

I can see server started, however when I try to login or list services it is giving connection closed error.
![image](https://user-images.githubusercontent.com/25299932/125202929-a4ed0a00-e293-11eb-8838-804fde0fb6d0.png)

Please help me in if I am missing anything.

Thanks,
Sreenatha

**Comment by asim** [comment]
There is no support for self deployment
