### ISSUE TITLE
Meme API

### ISSUE THREAD

**Issue by asim** [micro/services#302]
Bringing memes to the Micro platform

**Comment by h1z3y3** [comment]
That would be interesting, ;D

**Comment by BasToTheMax** [comment]
Use the Reddit api of r/memes

**Comment by h1z3y3** [comment]
@BasToTheMax 
I've checked /reddit/memes early.
Is there an easy with to deal with the OAuth 2.0 in API ?

Because I saw that reddit is only support OAuth2.0.
You can only get yourself profile information by using APIKEY.

**Comment by BasToTheMax** [comment]
I found a api that provides memes: https://api.popcat.xyz/meme
Now we only have to make a proxy

**Comment by h1z3y3** [comment]
Good, but it's easy to code 429. 😂

![image](https://user-images.githubusercontent.com/12080364/145845901-f119aca3-31db-4567-9726-e5ee3d51c2f1.png)

**Comment by asim** [comment]
Meme gen

https://github.com/micro/services/commit/0a06c3de0cb67a0d1f7f24b5cc574935e76efc14
