### ISSUE TITLE
Contact API

### ISSUE THREAD

**Issue by asim** [micro/services#311]
Store your contacts

**Comment by h1z3y3** [comment]
I'm going to work on it.

**Comment by h1z3y3** [comment]
@asim  Shall I use Postgres, the search feature in key-value DB is hard to implement.

**Comment by h1z3y3** [comment]
I misunderstand. 
If we use micro Store, it looks like doesn't have the search feature.

**Comment by asim** [comment]
A search API is coming soon. There's a branch for it but no PR yet. 

For now I'd do some sort of rudimentary local indexing using something like https://github.com/blevesearch/bleve

**Comment by h1z3y3** [comment]
Can't wait for it. 👍
