### ISSUE TITLE
Carbon API

### ISSUE THREAD

**Issue by asim** [micro/services#312]
Carbon offsetting API

**Comment by h1z3y3** [comment]
Could you give more information about it ?

**Comment by asim** [comment]
Basically something like using patch.io or an equivalent to do carbon offsetting. We want an API that will allow you to contribute back to becoming carbon neutral. The Offset endpoint would start by being priced at $1 and we'd provide alternate endpoints later to add more, otherwise you'd just call the endpoint multiple times to continue to offset.

**Comment by asim** [comment]
Done.
