### ISSUE TITLE
TODO: Replace DB with Store

### ISSUE THREAD

**Issue by asim** [micro/services#315]
Replaced DB usage with Store in the following services

- [x] Function
- [ ] User

**Comment by h1z3y3** [comment]
@asim , I've implemented most functions, but get confused about `Search()` function.
How to implement `Query` function with Store?

https://github.com/micro/services/blob/3cdf5baa23a82adc188764e10c621fbeaa229ee9/user/domain/domain.go#L377-L391

**Comment by h1z3y3** [comment]
At first, I think I can create multiple keys, like 

`/user/account/{user_id}`
`/user/account/{username}`
`/user/account/{email}`

But there may be some problems when do `Update` action.

**Comment by asim** [comment]
So you can probably go back into the history of the code there to see the original that used the store. When you have queries that have multiple possible params you basically store a record per query type aka denormalise the data. 

So you'll have a key that's userByEmail/ and userByUsername/ where the keys include the email or username to make the query an O(1) operation.

**Comment by asim** [comment]
We will also have to address migration of the data. So that'll require an on start operation that reads all the existing data and rewrites it with the new keys.

**Comment by h1z3y3** [comment]
> So you can probably go back into the history of the code there to see the original that used the store. When you have queries that have multiple possible params you basically store a record per query type aka denormalise the data. 
> 
> 
> 
> So you'll have a key that's userByEmail/ and userByUsername/ where the keys include the email or username to make the query an O(1) operation. 
> 
> 
> 
> And yes updates require updates to all keys. So writes are slower but reads are fast.

What confused me is that if we store user with username key or email key, when update user's email or username with new value, how deal with the old email key and username key.

For example, an user with email 'old-email@email.com'. There are 'user/id/1' and 'user/email/old-email@email.com' keys in Store. 

But when the user want to update his email to 'new-email@email.com'. 

How to deal with the old key 'user/email/old-email@email.com'?

**Comment by asim** [comment]
You have to effectively delete the old key and create a new one. During the update you see if the old email matches the one provided, if it does, nothing to do, if it changes you have to delete the old record.

**Comment by h1z3y3** [comment]
I don't find any doc about micro Store transaction, 
it doesn't support transaction, does it?
