### ISSUE TITLE
exec: "go": executable file not found in $PATH

### ISSUE THREAD

**Issue by ffreemt** [micro/services#32]
Hello.
I followed https://micro.mu/getting-started#getting-started upto `micro run github.com/micro/services/helloworld` and got `"go": executable file not found in $PATH` error message.
    ~# ls -l `which go`
    -rwxr-xr-x 1 root root 14244478 Dec  3 17:35 /usr/local/go/bin/go
    ~# micro run github.com/micro/services/helloworld
    exec: "go": executable file not found in $PATH
But `go` apparently is in $PATH. What could be the problem? 

Thanks

**Comment by chasnooker** [comment]
@ffreemt 
What was the issue in the end?
I came across the same one. 
Thanks

**Comment by sytgj7896321** [comment]
Before you start your `micro server`, please make sure `go` has in PATH, or you should restart your `micro server`
