### ISSUE TITLE
App(Beta) - unable to deploy an app from specified branch  

### ISSUE THREAD

**Issue by lambdaR** [micro/services#331]
The app.Run endpoint returns `{"Id":"app.run","Code":500,"Detail":"Failed to download source","Status":"Internal Server Error"}` for the following request.
```go
rsp, err := appService.Run(&app.RunRequest{
		Branch: "debo",
		Name:   "pwm3oappsdebo",
		Port:   8080,
		Region: "europe-west1",
		Repo:   "github.com/lambdaR/playing-with-m3o-apps",
	})
``` 
the same also with branch `zeus`.
`main` branch works fine.

**Comment by asim** [comment]
I'll have a look at this later today. I think it's because there might be a problem with the underlying library checking out the code. The codepath if you specify a https:// URL is different.

**Comment by asim** [comment]
Fixed, tested and running here https://lambda.m3o.app/
