### ISSUE TITLE
App(Beta) - fix the examples if the intended behavior is to return a raw backend endpoint.

### ISSUE THREAD

**Issue by lambdaR** [micro/services#332]
Currently, app.Status endpoint returns the raw backend endpoint.

it returns `https://myhelloworld-jn5gibw2pa-ew.a.run.app` instead of `https://myhelloworld.m3o.app` as an example.

Either the example needs to be fixed or implementation needs to be adjusted.

**Comment by asim** [comment]
This should now be fixed.
