### ISSUE TITLE
App(Beta) - DeploymentError when using asia-east1 region

### ISSUE THREAD

**Issue by lambdaR** [micro/services#335]
app.Status endpoint returns `{"Id":"app.status","Code":400,"Detail":"service does not exist","Status":"Bad Request"}` after running app.Run with this request 
```go
rsp, err := appService.Run(&app.RunRequest{
		Branch: "zeus",
		Name:   "pwm3oappszeus",
		Port:   8080,
		Region: "asia-east1",
		Repo:   "github.com/lambdaR/playing-with-m3o-apps",
	})
```

the app.List shows that there was a deployment error `{zeus 2021-12-16T14:00:58.844043522Z  map[] pwm3oappszeus pwm3oappszeus 8080 asia-east1 github.com/lambdaR/playing-with-m3o-apps DeploymentError  https://pwm3oappszeus.m3o.app}`

**Comment by lambdaR** [comment]
`us-central1` a similar case too.

**Comment by asim** [comment]
New regions I added without testing deployment. Requires creation of an artifact registry which became an interactive prompt and broke the deployment. Trying deleting and recreating.

**Comment by lambdaR** [comment]
i have tested it with **us-east1** just now, this is the result `{zeus 2021-12-16T16:42:41.940407719Z  map[] pwm3oappszeus pwm3oappszeus 8080 us-east1 github.com/lambdaR/playing-with-m3o-apps DeploymentError  https://pwm3oappszeus.m3o.app}` 

Is this the latest version of go clients `v0.5.1-0.20211216154900-3c6466378cc4` ? this is the version i am running the test with.

**Comment by asim** [comment]
OK so I understand what this issue is. There's an artifact registry per region, those did not exist, the service account did not have permission to create it. So I've fixed that.

**Comment by lambdaR** [comment]
it works now ... closing
