### ISSUE TITLE
Minecraft Server Ping API

### ISSUE THREAD

**Issue by BasToTheMax** [micro/services#357]
This api checks if a Minecraft server is online or not

**Comment by asim** [comment]
I can imagine writing a generic ping service unless minecraft has some specific protocol. Assuming there's a http endpoint?

**Comment by BasToTheMax** [comment]
Minecraft uses TCP

**Comment by asim** [comment]
Alright so let's say its a ping service that supports http and tcp

service Ping {
    Url(...)
    Tcp(...)
    Ip(...)
    // other protocols
    ...
    // ping on an interval
    Monitor(...)
}

Make sense?

**Comment by BasToTheMax** [comment]
> Alright so let's say its a ping service that supports http and tcp
> 
> ```
> service Ping {
>     Url(...)
>     Tcp(...)
>     Ip(...)
>     // other protocols
>     ...
>     // ping on an interval
>     Monitor(...)
> }
> ```
> 
> Make sense?

Yeah. Exactly like that!

**Comment by asim** [comment]
Any comments on pricing? Free for one off checks, paid monitoring?

**Comment by asim** [comment]
https://github.com/micro/services/pull/372

No interval yet

**Comment by asim** [comment]
Dupe of https://github.com/micro/services/issues/285

**Comment by asim** [comment]
Actually. I'm going to add a separate minecraft service specifically for minecraft ping

**Comment by asim** [comment]
https://m3o.com/minecraft
