### ISSUE TITLE
Weather: Missing attributes in response example

### ISSUE THREAD

**Issue by cyb3rko** [micro/services#391]
The attributes listed under "Response" are not shown in the response example on the right except for "forecast".
Furthermore the "forecast" example response is missing 2 attributes:
- chance_of_rain
- will_it_rain

![image](https://user-images.githubusercontent.com/46033730/156010484-511816ca-e419-4baa-a11b-54bf43d61950.png)

![image](https://user-images.githubusercontent.com/46033730/156010574-4c12e865-d6e0-4dd8-88d7-0842a2b479ba.png)

**Comment by asim** [comment]
The example can be updated here https://github.com/micro/services/blob/master/weather/examples.json
