### ISSUE TITLE
How can we start this project?

### ISSUE THREAD

**Issue by cesc1802** [micro/services#434]
![image](https://user-images.githubusercontent.com/16495198/195038007-1c53513e-975a-4ee7-9dca-6c41f95d7349.png)
I'll try to run example project by using the command is `micro run github.com/micro/services/helloworld` but I faced with error mentioned in the image

**Comment by asim** [comment]
```
# run the micro server
micro server

# set env to local
micro env set local

# login (user: admin pass: micro)
micro login

# run the service
micro run github.com/micro/services/helloworld
````

If on windows execute as root user in powershell

**Comment by cesc1802** [comment]
thank you for your support. Why do we need to run the `micro server` first? what is the purpose of this command?

**Comment by asim** [comment]
Micro is a platform that provides an abstraction to underlying infrastructure and cloud services; including auth, storage, messaging, etc. The services are run on the Micro platform e.g like an operating system or PaaS. So you must first run the server aka `micro server` and then you can instruct it to run services using `micro run xxxx`. 

See https://micro.dev/docs for more info
